openapi: 3.1.0
info:
  title: Online-PPT Backend API
  version: 0.1.0
  description: REST API for user authentication and PPT record management.
servers:
  - url: http://localhost:8080/api/v1
paths:
  /auth/register:
    post:
      summary: Register a new user with email and password
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RegisterRequest'
      responses:
        '201':
          description: User created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthResponse'
        '400':
          description: Validation error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '409':
          description: Email already registered
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  /auth/login:
    post:
      summary: Authenticate user and issue tokens
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginRequest'
      responses:
        '200':
          description: Login successful
          headers:
            Set-Cookie:
              description: HttpOnly cookie containing refresh token (if configured)
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthResponse'
        '401':
          description: Invalid credentials
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  /auth/logout:
    post:
      summary: Revoke current session
      security:
        - AccessToken: []
      responses:
        '204':
          description: Logout successful
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  /auth/refresh:
    post:
      summary: Exchange refresh token for new access token
      responses:
        '200':
          description: New tokens issued
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthResponse'
        '401':
          description: Invalid or expired refresh token
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  /ppts:
    get:
      summary: List PPT records for current user
      security:
        - AccessToken: []
      parameters:
        - name: q
          in: query
          description: Keyword to search in name/description/tags
          schema:
            type: string
        - name: tag
          in: query
          schema:
            type: string
        - name: sort
          in: query
          schema:
            type: string
            enum: [created_at_desc, created_at_asc, name_asc]
        - name: limit
          in: query
          schema:
            type: integer
            default: 50
            maximum: 100
        - name: offset
          in: query
          schema:
            type: integer
            default: 0
      responses:
        '200':
          description: List of records
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PptRecordListResponse'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
    post:
      summary: Create a PPT record
      security:
        - AccessToken: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PptRecordCreateRequest'
      responses:
        '201':
          description: Record created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PptRecordResponse'
        '400':
          description: Validation error or path outside allowed root
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '409':
          description: Record with same path already exists for user
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  /ppts/{id}:
    get:
      summary: Fetch a single PPT record
      security:
        - AccessToken: []
      parameters:
        - $ref: '#/components/parameters/RecordId'
      responses:
        '200':
          description: Record details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PptRecordResponse'
        '404':
          description: Record not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
    patch:
      summary: Update a PPT record
      security:
        - AccessToken: []
      parameters:
        - $ref: '#/components/parameters/RecordId'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PptRecordUpdateRequest'
      responses:
        '200':
          description: Record updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PptRecordResponse'
        '400':
          description: Validation error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '404':
          description: Record not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
    delete:
      summary: Delete a PPT record
      security:
        - AccessToken: []
      parameters:
        - $ref: '#/components/parameters/RecordId'
      responses:
        '204':
          description: Record deleted
        '404':
          description: Record not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
components:
  securitySchemes:
    AccessToken:
      type: http
      scheme: bearer
      bearerFormat: JWT
  parameters:
    RecordId:
      name: id
      in: path
      required: true
      schema:
        type: integer
        format: int64
  schemas:
    RegisterRequest:
      type: object
      required: [email, password]
      properties:
        email:
          type: string
          format: email
        password:
          type: string
          minLength: 10
    LoginRequest:
      type: object
      required: [email, password]
      properties:
        email:
          type: string
          format: email
        password:
          type: string
    AuthResponse:
      type: object
      properties:
        user:
          $ref: '#/components/schemas/User'
        accessToken:
          type: string
          description: Short-lived JWT access token
        expiresIn:
          type: integer
          description: Access token validity window in seconds
    User:
      type: object
      properties:
        id:
          type: integer
          format: int64
        email:
          type: string
          format: email
        status:
          type: string
          enum: [active, locked, pending]
        lastLoginAt:
          type: string
          format: date-time
          nullable: true
    PptRecordCreateRequest:
      type: object
      required: [name]
      properties:
        name:
          type: string
          maxLength: 120
          pattern: '^[A-Za-z0-9_-]+$'
          description: Display name and folder group identifier
        description:
          type: string
          maxLength: 500
          nullable: true
        tags:
          type: array
          items:
            type: string
          maxItems: 10
    PptRecordUpdateRequest:
      type: object
      properties:
        name:
          type: string
          maxLength: 120
          pattern: '^[A-Za-z0-9_-]+$'
          description: If changed, server regenerates folder name
        description:
          type: string
          maxLength: 500
          nullable: true
        tags:
          type: array
          items:
            type: string
          maxItems: 10
    PptRecordResponse:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        groupName:
          type: string
        description:
          type: string
          nullable: true
        relativePath:
          type: string
          description: Relative path in format presentations/<user-uuid>/<group>/slides
        canonicalPath:
          type: string
        tags:
          type: array
          items:
            type: string
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time
        pathStatus:
          type: string
          enum: [valid, missing, outside_root]
      required: [id, name, relativePath, canonicalPath, createdAt, updatedAt, pathStatus]
    PptRecordListResponse:
      type: object
      properties:
        total:
          type: integer
        limit:
          type: integer
        offset:
          type: integer
        items:
          type: array
          items:
            $ref: '#/components/schemas/PptRecordResponse'
    ErrorResponse:
      type: object
      properties:
        code:
          type: string
        message:
          type: string
        details:
          type: object
          additionalProperties: true
